insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (1, 'NASDAQ', 'Amtech Systems, Inc.', 100690, 71);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (2, 'NYSE', 'AmTrust Financial Services, Inc.', 141396, 66);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (3, 'NASDAQ', 'The First of Long Island Corporation', 104314, 45);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (4, 'NASDAQ', 'KraneShares CSI China Internet ETF', 83505, 9);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (5, 'NASDAQ', 'Reading International Inc', 69045, 82);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (6, 'NASDAQ', 'Soligenix, Inc.', 104270, 19);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (7, 'NYSE', 'Tronox Limited', 151446, 33);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (8, 'NYSE', 'Maiden Holdings, Ltd.', 8343, 68);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (9, 'NYSE', 'Seabridge Gold, Inc.', 63162, 6);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (10, 'NASDAQ', 'iShares S&P Global Timber & Forestry Index Fund', 29712, 43);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (11, 'NYSE', 'Fly Leasing Limited', 159292, 43);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (12, 'NYSE', 'Universal Technical Institute Inc', 152015, 68);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (13, 'NASDAQ', 'Forum Merger Corporation', 62782, 17);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (14, 'NASDAQ', 'Middlefield Banc Corp.', 111078, 6);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (15, 'NASDAQ', 'QAD Inc.', 8014, 85);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (16, 'NYSE', 'SPX Corporation', 100663, 40);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (17, 'NYSE', 'Lehman ABS Corporation', 198225, 75);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (18, 'NYSE', 'Och-Ziff Capital Management Group LLC', 51065, 5);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (19, 'NASDAQ', 'Commerce Bancshares, Inc.', 1726, 17);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (20, 'NYSE', 'Stifel Financial Corporation', 113914, 99);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (21, 'NASDAQ', 'Bank of Marin Bancorp', 103421, 59);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (22, 'NYSE', 'Navigant Consulting, Inc.', 43538, 90);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (23, 'NASDAQ', 'PAVmed Inc.', 114284, 99);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (24, 'NASDAQ', 'Heartland Financial USA, Inc.', 134457, 16);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (25, 'NYSE', 'Centrais Electricas Brasileiras S.A.- Eletrobras', 39000, 66);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (26, 'NYSE', 'Regal Entertainment Group', 68335, 17);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (27, 'NYSE', 'Natuzzi, S.p.A.', 20163, 2);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (28, 'NASDAQ', 'Vertex Pharmaceuticals Incorporated', 161641, 52);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (29, 'NASDAQ', 'Solar Senior Capital Ltd.', 129150, 98);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (30, 'NYSE', 'Parker Drilling Company', 114212, 80);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (31, 'NYSE', 'TCW Strategic Income Fund, Inc.', 69700, 94);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (32, 'NASDAQ', 'WSFS Financial Corporation', 37178, 96);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (33, 'NASDAQ', 'Rightside Group, Ltd.', 182123, 85);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (34, 'NYSE', 'Pebblebrook Hotel Trust', 114436, 28);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (35, 'NYSE', 'RAIT Financial Trust', 30680, 46);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (36, 'NASDAQ', 'Syneron Medical Ltd.', 94218, 60);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (37, 'NASDAQ', 'People''s United Financial, Inc.', 6593, 24);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (38, 'NASDAQ', 'PowerShares Golden Dragon China Portfolio', 37439, 94);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (39, 'NYSE', 'Two Harbors Investments Corp', 156884, 47);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (40, 'NYSE', 'Berkshire Hathaway Inc.', 9092, 87);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (41, 'NASDAQ', 'Concurrent Computer Corporation', 30961, 61);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (42, 'NASDAQ', 'Bojangles'', Inc.', 171051, 41);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (43, 'NYSE', 'Vocera Communications, Inc.', 15248, 95);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (44, 'NYSE', 'Prologis, Inc.', 143101, 28);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (45, 'NYSE', 'Prudential Public Limited Company', 29984, 56);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (46, 'NASDAQ', 'Oncobiologics, Inc.', 1186, 56);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (47, 'NYSE', 'Black Knight Financial Services, Inc.', 110766, 77);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (48, 'NYSE', 'Citigroup Inc.', 41688, 75);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (49, 'NYSE', 'Jupai Holdings Limited', 50227, 4);
insert into tabla33 (product_code, product_name, product_brand, product_price, product_quantity) values (50, 'NASDAQ', 'Atlantic Capital Bancshares, Inc.', 97624, 72);
